compatibility_date = "2023-10-16"
pages_build_output_dir = "./dist"
name = "r2-webdav"

compatibility_flags = ["nodejs_compat"]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "bucket" # <~ valid JavaScript variable name
bucket_name = "webdav"

